### ISSUE TITLE
Connection issue to CLoudSQL(Postgres DB) - While insert data to DB

### ISSUE THREAD

**Issue by yogi0421** [GoogleCloudPlatform/cloud-sql-python-connector#777]
### Question

Hi all,

I try to insert data from FastAPI app deployed on GKE with `cloud-sql-python-connector`, but currently the service is unstable because the connection issue from FastAPI service(GKE) and CloudSQL - postgres DB, the detail error is like this
```
 Traceback (most recent call last):
  File "/app/app/database.py", line 19, in getconn
    conn = connector.connect(
  File "/usr/local/lib/python3.8/site-packages/google/cloud/sql/connector/connector.py", line 159, in connect
    return connect_task.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.8/site-packages/google/cloud/sql/connector/connector.py", line 240, in connect_async
    instance_data, ip_address = await instance.connect_info(ip_type)
  File "/usr/local/lib/python3.8/site-packages/google/cloud/sql/connector/instance.py", line 448, in connect_info
    instance_data = await self._current
  File "/usr/local/lib/python3.8/site-packages/google/cloud/sql/connector/instance.py", line 391, in _refresh_task
    refresh_data = await refresh_task
  File "/usr/local/lib/python3.8/site-packages/google/cloud/sql/connector/instance.py", line 315, in _perform_refresh
    metadata = await metadata_task
  File "/usr/local/lib/python3.8/site-packages/google/cloud/sql/connector/refresh_utils.py", line 93, in _get_metadata
    credentials.refresh(request)
  File "/usr/local/lib/python3.8/site-packages/google/auth/compute_engine/credentials.py", line 121, in refresh
    six.raise_from(new_exc, caught_exc)
  File "<string>", line 3, in raise_from
google.auth.exceptions.RefreshError: Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Engine metadata service. Compute Engine Metadata server unavailable 
```

![image](https://github.com/GoogleCloudPlatform/cloud-sql-python-connector/assets/26356739/f1756423-f7bb-4597-8b19-1cfddc27f501)

this issue cause error in my service, I already check the CloudSQL instance, but no issue on the CloudSQL instance.

if you any suggestion/solution about my issue, please inform to me. Thank you

![Screenshot 2023-06-30 at 10 40 14](https://github.com/GoogleCloudPlatform/cloud-sql-python-connector/assets/26356739/33ed20ca-b9a4-45cb-b39b-d1cd2a9d3b70)

### Code

```Python
### Start code for database.py file
import os
from sqlalchemy import create_engine, MetaData, Table
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker
from google.cloud.sql.connector import Connector, IPTypes

# Cloud SQL Python Connector creator function
def getconn():
    # if env var PRIVATE_IP is set to True, use private IP Cloud SQL connections
    ip_type = IPTypes.PRIVATE if os.getenv("PRIVATE_IP") is True else IPTypes.PUBLIC
    # if env var DB_IAM_USER is set, use IAM database authentication
    user, enable_iam_auth = (
        (os.getenv("DB_IAM_USER"), True)
        if os.getenv("DB_IAM_USER")
        else (os.getenv("DB_USER"), False)
    )
    # initialize Cloud SQL Python connector object
    with Connector(ip_type=ip_type, enable_iam_auth=enable_iam_auth) as connector:
        conn = connector.connect(
            os.getenv("CLOUD_SQL_INSTANCE"),
            "pg8000",
            user=user,
            password=os.getenv("DB_PASS", ""),
            db=os.getenv("DB_NAME"),
        )
        return conn


SQLALCHEMY_DATABASE_URL = "postgresql+pg8000://"

engine = create_engine(SQLALCHEMY_DATABASE_URL, creator=getconn)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)

Base = declarative_base()

MetaDataDB = MetaData()
# Reflect the database schema
MetaDataDB.reflect(bind=engine)
### End code for database.py



### start code for models.py
from sqlalchemy import Column, DateTime, Integer, String, Float
from app.database import Base

def create_models_fs(tablename):

    class FSCstripInsert(Base):
        __tablename__ = tablename
        __table_args__ = {'extend_existing': True}

        uuid = Column(String, primary_key=True)
        raw_data =  Column(String, index=True)
        cooked_data =  Column(String, index=True)
        result =  Column(String, index=True)
        created_at =  Column(DateTime, index=True)

        def __init__(self, uuid, raw_data, cooked_data, result, created_at):
            self.uuid = uuid
            self.raw_data = raw_data
            self.cooked_data = cooked_data
            self.result = result
            self.created_at = created_at

    return FSCstripInsert
### end code for models.py


### start code for operations.py
from datetime import datetime, timezone

from sqlalchemy.orm import Session
from sqlalchemy import desc
from sqlalchemy import and_, or_, not_

import app.models
import app.models as app_model
import json

def create_records(db: Session, table_name, uuid_data: str, raw_data: str, cooked_data: str, result: str):
    new_table = app_model.create_models_fs(
            tablename=table_name,
        )
    
    new_records = new_table(
        uuid_data,
        raw_data,
        cooked_data,
        result,
        datetime.now(tz=timezone.utc)
    )
    db.add(new_records)
    db.commit()
    return new_records
### end code for operations.py


### start code for main FastAPI/api.py
from fastapi import FastAPI, Body, Depends, Header, status, HTTPException, Request, Form
from fastapi.responses import HTMLResponse
from fastapi.templating import Jinja2Templates
## ...

@app.post('/v1/general/insert-fs-data/{tbl_name}/',
                          tags=["Insert Data"],
                          description="Insert data to Feature Store."
                    )
async def insert_to_feature_store(
        tbl_name: str,
        models: BaseFunctionFeatureStore = Body(
            example={...}
        ),
        ml_token: Union[str, None] = Header(default=None, convert_underscores=False),
        db: Session = Depends(get_db)
    ):
    if mltoken['key'] == ml_token:
        get_data = dict(models)
        start = time.time()
        get_data['created_at'] = str(datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
        raw_data = get_data['data']

        req_data_key = list(raw_data.keys())
        dtype = [await data_type(raw_data[k]) for k in raw_data.keys()]
        request_dtype = {k: v for k, v in zip(req_data_key, dtype)}
        print("\ndictionary request_dtype : ", request_dtype)

        table_prop = Table(tbl_name, MetaDataDB, autoload=True)

        new_data = operations.create_records(
            db,
            tbl_name,
            uuid_data=str(raw_data['uuid']),
            raw_data=str(json.dumps(raw_data['raw_data'])),
            cooked_data=str(json.dumps(raw_data['cooked_data'])), 
            result=str(json.dumps(raw_data['result']))
        )
        fs_response = "Data with UUID : {} Success inert to table {} ...".format(raw_data['uuid'], tbl_name)
        print("fs_response : ", fs_response)

        return {
            "msg": fs_response,
            "timestamp": str(datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
        }

    else:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Forbidden"
        )
### end code for main FastAPI/api.py
```

**Comment by yogi0421** [comment]
Hi @jackwotherspoon, thanks for the answer

for the IAM Role I already attach to deployment on GKE, even the GKE Cluster I create, I grant the full GCP access API and if I double check the service account role is same role with another environment(dev and staging).

1. Is your Cloud SQL instance in the same Google Cloud project as your application (GKE cluster)?
Yes, The CloudSQL instance in the same GCP project with GKE cluster.

2. Are you using a Public IP or Private IP Cloud SQL instance?
for the connection I used public IP.

This is my yaml deployment config
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-service-name
  namespace: dev-ml-services
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: dev-service-name
  template:
    metadata:
      labels:
        app: dev-service-name
    spec:
      containers:
      - name: dev-service-name
        image: asia.gcr.io/GCP_PROJECT_ID/service-name-image:dev-build-39
        ### Read K8s secret config
        env:
          - name: MLTOKEN
            valueFrom:
              secretKeyRef:
                name: feature-store-connection
                key: mltoken
          - name: INSTANCE_HOST
            valueFrom:
              secretKeyRef:
                name: feature-store-connection
                key: instancehost
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: feature-store-connection
                key: dbuser
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: feature-store-connection
                key: dbpass
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: feature-store-connection
                key: dbname
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: feature-store-connection
                key: dbport
          - name: CLOUD_SQL_INSTANCE
            valueFrom:
              secretKeyRef:
                name: feature-store-connection
                key: cloudsqlinstance
          - name: SERVICE_ACCOUNT
            valueFrom:
              secretKeyRef:
                name: feature-store-connection
                key: serviceaccount
      - name: cloud-sql-proxy
        image:  gcr.io/cloud-sql-connectors/cloud-sql-proxy:latest
        command:
          - "--port=5432"
          - "GCP_PROJECT_ID:GCP_REGION:CLOUD_SQL_INSTANCE_NAME=tcp:5432"
        securityContext:
          runAsNonRoot: true

---
apiVersion: v1
kind: Service
metadata:
  name: dev-service-name
  namespace: dev-ml-services
  labels:
    app: dev-service-name
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: dev-service-name
  selector:
    app: dev-service-name
  type: LoadBalancer
  loadBalancerIP: "-.-.-.-"
```

**Comment by jackwotherspoon** [comment]
Hi @yogi0421 after thinking about this a little more I think the cause of the error you are seeing is most likely due to the pod having some type of permissions/networking issue blocking traffic to the metadata server (used as part of google-auth dependency to refresh access token/creds). You may want to take a close look at your GKE configuration and make sure there aren't any restrictive permissions on your pod.

In the meantime I will try and see if I can reproduce the error myself.

Note: I noticed you are also deploying the `cloud-sql-proxy`, this is not required if you are using the Cloud SQL Python Connector as it is a direct in process replacement of the Proxy. You should be able to remove the following from your yaml:
```yaml
- name: cloud-sql-proxy
        image:  gcr.io/cloud-sql-connectors/cloud-sql-proxy:latest
        command:
          - "--port=5432"
          - "GCP_PROJECT_ID:GCP_REGION:CLOUD_SQL_INSTANCE_NAME"
        securityContext:
          runAsNonRoot: true
```
